embeds/urls.py
from django.urls import path

from . import views

app_name = 'embeds'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:embed_id>/', views.detail, name='detail'),
    path('<int:embed_id>/', views.add, name='add'),
    path('list', views.list, name='list'),
    path('signup', views.signup, name='signup'),
]

tacho_streaming/urls.py
from django.contrib import admin
from django.urls import include, path
from django.shortcuts import redirect

urlpatterns = [
    path('', lambda req: redirect('/embeds/')),
    path('embeds/', include('embeds.urls')),
    path('admin/', admin.site.urls),
]

embeds/models.py
from typing import Text
from django.db import models
from django.db.models.deletion import CASCADE
from django.db.models.fields import CharField, DateTimeField, URLField
from django.conf import settings
import datetime

# Create your models here.

PLATFORMS = (
    ('YouTube', 'YouTube'),
    ('Vimeo', 'Vimeo'),
)

class Embed(models.Model):
    title = CharField(max_length=200, default="Evento Sin Nombre")
    event_url = URLField(max_length=200)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=CASCADE, related_name='creator')
    creation_date = DateTimeField(auto_now_add=True)
    last_modification_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=CASCADE, related_name='last_editor')
    last_modification = DateTimeField(auto_now=True)
    platform = CharField(max_length=20, choices=PLATFORMS)

class Modification(models.Model):
    previous_title = models.ForeignKey(Embed, on_delete=CASCADE, related_name='previous_name', null=True)
    new_title = CharField(max_length=200, default="Evento Sin Nombre")
    previous_url = URLField(max_length=200)
    new_url = URLField(max_length=200)
    modified_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=CASCADE, related_name='editor')
    modification_date = DateTimeField(auto_now_add=True)

embeds/views.py
from django.db.models import query
from django.shortcuts import redirect, render

# Create your views here.
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages

from .models import Embed

def signup(request):
    if request.user.is_authenticated:
        return redirect('embed:index')
    if request.method == 'POST':
        f = UserCreationForm(request.POST)
        if f.is_valid():
            f.save()
            messages.success(request, 'Account created successfullly')
            return redirect('signup')
    else:
        f = UserCreationForm()
    return render(request, 'embeds/signup.html', {'form': f})

def index(request):
    
    try:
        last_embed = Embed.objects.order_by('-creation_date')[0]
        latest_embed_list = Embed.objects.order_by('-creation_date')[1:6]
        context = {
            'last_embed': last_embed,
            'latest_embed_list': latest_embed_list,
        }
        return render(request, 'embeds/index.html', context)
    except IndexError:
        raise Http404('There are no embeds')

def detail(request, embed_id):
    embed = get_object_or_404(Embed, pk=embed_id)
    return render(request, 'embeds/detail.html', {'embed': embed})

def list(request):
    embed_list = Embed.objects.all()
    return render(request, 'embeds/list.html', {'embed_list': embed_list}) 

def add(request, embed_id):
    return render(request, 'embeds/add.html', {'embed_id': embed_id})

embeds/templates/embeds/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Compiled and minified CSS -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <!-- Compiled and minified JavaScript -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <title>{% block title %}TACHO Streaming{% endblock %}</title>
    </head>
    <body>

        <nav>
            <div class="nav-wrapper grey darken-4">    
                <a href="{% url 'embeds:index' %}" class="brand-logo">TACHO PRODUCCIONES</a>
                <ul id="nav-mobile" class="right hide-on-med-and-down">
                    <li><a href="{% url 'embeds:list' %}">Lista</a></li>
                </ul>
            </div>
        </nav>

        {% block content %}

        {% endblock %}

    </body>
</html>

embeds/templates/embeds/detail.html
{% extends "embeds/base.html" %}

{% block content %}

    <h2>{{ embed.title }}</h2>
    <div class="video-container">
        <iframe
        src="{{ embed.event_url }}/embed"
        frameborder="0"
        allowfullscreen
        ></iframe>
    </div>
    
{% endblock %}

embeds/templates/embeds/index.html
{% extends "embeds/base.html" %}

{% block content %}

    {% if latest_embed_list %}
        {% if last_embed %}
        <h2>{{ last_embed.title }}</h2>
        <div class="video-container">
            <iframe
            src="{{ last_embed.event_url }}/embed"
            frameborder="0"
            allowfullscreen
            ></iframe>
        </div>
        {% endif %}
        
        <br><br>

    <table class="centered highlight responsive-table">
      <tr>
        <th>Titulo</th>
        <th>URL Transmision</th>
        <th>Fecha Creacion</th>
        <th>Creado por</th>
        <th>Ultima Modificacion</th>
        <th>Modificado por</th>
        <th>Plataforma</th>
        <th>Transmision</th>
      </tr>
      {% for item in latest_embed_list %}
      <tr>
        <td>{{ item.title }}</td>
        <td>{{ item.event_url }}</td>
        <td>{{ item.creation_date }}</td>
        <td>{{ item.created_by }}</td>
        <td>{{ item.last_modification }}</td>
        <td>{{ item.last_modification_by }}</td>
        <td>{{ item.platform }}</td>
        <td>
          <a href="{% url 'embeds:detail' item.id %}">Ver Transmision</a>
        </td>
      </tr>
      {% endfor %}
    </table>
    {% else %}
    <p>No hay eventos disponibles.</p>

    {% endif %}

{% endblock %}

embeds/templates/embeds/list.html
{% extends "embeds/base.html" %}

{% block content %}
    {% if embed_list %}
    <table class="centered highlight responsive-table">
        <tr>
            <th>Titulo</th>
            <th>Embed URL</th>
            <th>Fecha Creacion</th>
            <th>Creado por</th>
            <th>Ultima Modificacion</th>
            <th>Modificado por</th>
            <th>Plataforma</th>
            <th>Transmision</th>
        </tr>
        {% for item in embed_list %}
        <tr> 
            <td>{{ item.title }}</td>
            <td>{{ item.event_url }}</td>
            <td>{{ item.creation_date }}</td>
            <td>{{ item.created_by }}</td>
            <td>{{ item.last_modification }}</td>
            <td>{{ item.last_modification_by }}</td>
            <td>{{ item.platform }}</td>
            <td><a href="{% url 'embeds:detail' item.id %}">Ir a la transmision</a></td>
        </tr>
        {% endfor %}
    </table>
    {% else %}
    <p>No embeds are available.</p>

    {% endif %}
{% endblock %}

embeds/templates/embeds/signup.html
{% extends "embeds/base.html"  %}

{% block title %}
    Sign Up - {{ block.super }}
{% endblock %}

{% block main %}

    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-6">
            <h4>Sign Up</h4>
            <hr>
            {% if messages %}
                {% for message in messages %}
                    <p class="alert alert-info">{{ message }}</p>
                {% endfor %}
            {% endif %}

            <form method="post">

                {% csrf_token %}

                <table class="table">
                    {{ form.as_table }}
                    <tr>
                        <td><input type="hidden" name="next" value="{{ next }}"></td>
                        <td><button type="submit" class="btn btn-primary">Submit</button></td>
                    </tr>
                </table>

            </form>
        </div>

        <div class="col-lg-6 col-md-6 col-sm-6">
            <h4>Related Links</h4>
            <p>
                <a href="/reset-password/">Forgot Password?</a> <br>
                <a href="{% url 'djangobin:login' %}">Login.</a> <br>
            </p>
        </div>

    </div>

{% endblock %}